apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dev-argocd
spec:
  selector:
    matchLabels:
      app: test-dev-argocd
  replicas: 2
  template:
    metadata:
      labels:
        app: test-dev-argocd
    spec:
      containers:
      - name: test-dev-argocd
        image: wilsonggr/my-spring-boot-app
        ports:
        - containerPort: 8080
