apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-argocd-service
spec:
  selector:
    matchLabels:
      app: test-argocd-service
  replicas: 2
  template:
    metadata:
      labels:
        app: test-argocd-service
    spec:
      containers:
      - name: test-argocd-service
        image: wilsonggr/my-spring-boot-app
        ports:
        - containerPort: 3000
