apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdDevnamespace
spec:
  selector:
    matchLabels:
      app: argocdDevnamespace
  replicas: 2
  template:
    metadata:
      labels:
        app: argocdDevnamespace
    spec:
      containers:
      - name: argocdDevnamespace
        image: wilsonggr/my-spring-boot-app
        ports:
        - containerPort: 8080

