apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dev
spec:
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - name: guestbook-ui
        image: wilsonggr/my-spring-boot-app
         resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80