apiVersion: apps/v1
kind: Deployment
metadata:
  name: myargoapp
spec:
  selector:
    matchLabels:
      app: myargoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myargoapp
    spec:
      containers:
      - name: myargoapp
        image: wilsonggr/my-spring-boot-app
        ports:
        - containerPort: 8080

