apiVersion: v1
name: my-spring-boot-app
description: The proxy Helm Chart targeting the ovia-prerequisites-syncers Helm chart
version: 0.0.0
dependencies:
  - name: my-spring-boot-app
    version: 0.0.0
    repository: https://github.com/wigali/argoCDDevelopment